force-app/main/default/objects/Report_Subscription__mdt/fields/Column_1__c.field-meta.xml
<CustomField>
    <fullName>Column_1__c</fullName>
    <label>Column 1</label>
    <metadataRelationshipControllingField>Report_Subscription__mdt.Source_Object__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>Report_Subscriptions</relationshipLabel>
    <relationshipName>Report_Subscriptions</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Report_Subscription__mdt/fields/Column_2__c.field-meta.xml
<CustomField>
    <fullName>Column_2__c</fullName>
    <label>Column 2</label>
    <metadataRelationshipControllingField>Report_Subscription__mdt.Source_Object__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>Report_Subscriptions1</relationshipLabel>
    <relationshipName>Report_Subscriptions1</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Report_Subscription__mdt/fields/Column_3__c.field-meta.xml
<CustomField>
    <fullName>Column_3__c</fullName>
    <label>Column 3</label>
    <metadataRelationshipControllingField>Report_Subscription__mdt.Source_Object__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>Report_Subscriptions2</relationshipLabel>
    <relationshipName>Report_Subscriptions2</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Report_Subscription__mdt/fields/Column_4__c.field-meta.xml
<CustomField>
    <fullName>Column_4__c</fullName>
    <label>Column 4</label>
    <metadataRelationshipControllingField>Report_Subscription__mdt.Source_Object__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>Report_Subscriptions3</relationshipLabel>
    <relationshipName>Report_Subscriptions3</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Report_Subscription__mdt/fields/Source_Object__c.field-meta.xml
<CustomField>
    <fullName>Source_Object__c</fullName>
    <description>The primary data table to include in the report</description>
    <inlineHelpText>The primary data table to include in the report</inlineHelpText>
    <label>Source Object</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Report_Subscriptions</relationshipLabel>
    <relationshipName>Report_Subscriptions</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Report_Subscription__mdt/fields/To_Addresses__c.field-meta.xml
<CustomField>
    <fullName>To_Addresses__c</fullName>
    <description>Email addresses to send results to, separated by commas</description>
    <inlineHelpText>Email addresses to send results to, separated by commas</inlineHelpText>
    <label>To Addresses</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/ReportSubscriptionBatch.cls
public with sharing class ReportSubscriptionBatch implements Database.Batchable<sObject> {
    
    public Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'SELECT Id, Source_Object__c, Column_1__c, Column_2__c, Column_3__c, Column_4__c, Filter_Criteria__c, To_Addresses__c FROM Report_Subscription__mdt LIMIT 10000';
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<Report_Subscription__mdt> lstSubs) {
        ReportSubscriptionHandler.sendData(lstSubs);
    }

    public void finish(Database.BatchableContext bc) {
        AsyncApexJob apexJob = [
            SELECT Id, 
                   Status, 
                   NumberOfErrors, 
                   JobItemsProcessed, 
                   TotalJobItems, 
                   CreatedBy.Email
              FROM AsyncApexJob 
             WHERE Id = :bc.getJobId()
        ];
        
        // Send email to job creator with batch results
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
        String[] toAddress = new String[] {apexJob.CreatedBy.Email};
        email.setToAddresses(toAddress);
        email.setSubject(apexJob.Status + ': Report Subscription Batch');
        email.setPlainTextBody('The Report Subscription ran and processed ' + apexJob.TotalJobItems + ' batches with ' + apexJob.NumberOfErrors + ' failures. Job Id: ' + apexJob.Id);
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { email });
    }

}